version: "3.3"
services:
  kag:
    restart: always
    network_mode: "host"  # use host networking to improve latency
    build:
      context: . 
      dockerfile: Dockerfile.kag
    volumes:
      - ./autoconfig.cfg:/kag/autoconfig.cfg
      - ./mods.cfg:/kag/mods.cfg:ro
      - ./Mods:/kag/Mods:ro
      - ./Security:/kag/Security:ro
      - ./Logs:/kag/Logs
      - ./Cache:/kag/Cache